# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='message.proto',
  package='tinyMQ',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rmessage.proto\x12\x06tinyMQ\";\n\x08\x43onnInit\x12\x0c\n\x04role\x18\x01 \x02(\x07\x12\r\n\x05topic\x18\x02 \x02(\t\x12\x12\n\nauth_token\x18\x03 \x01(\t\"\x1c\n\nConnStatus\x12\x0e\n\x06status\x18\x01 \x02(\x07\"7\n\x0c\x43ontentWrite\x12\n\n\x02id\x18\x01 \x02(\x07\x12\r\n\x05topic\x18\x02 \x02(\t\x12\x0c\n\x04\x62ody\x18\x03 \x02(\x0c\"\x15\n\x04Poll\x12\r\n\x05topic\x18\x01 \x02(\t\" \n\x03\x41\x63k\x12\n\n\x02id\x18\x01 \x02(\x07\x12\r\n\x05\x66lags\x18\x02 \x01(\x07\"7\n\x0b\x43ontentRead\x12\n\n\x02id\x18\x01 \x02(\x07\x12\x0e\n\x06status\x18\x02 \x02(\x07\x12\x0c\n\x04\x62ody\x18\x03 \x02(\x0c'
)




_CONNINIT = _descriptor.Descriptor(
  name='ConnInit',
  full_name='tinyMQ.ConnInit',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='role', full_name='tinyMQ.ConnInit.role', index=0,
      number=1, type=7, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='topic', full_name='tinyMQ.ConnInit.topic', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='auth_token', full_name='tinyMQ.ConnInit.auth_token', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=84,
)


_CONNSTATUS = _descriptor.Descriptor(
  name='ConnStatus',
  full_name='tinyMQ.ConnStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='tinyMQ.ConnStatus.status', index=0,
      number=1, type=7, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=86,
  serialized_end=114,
)


_CONTENTWRITE = _descriptor.Descriptor(
  name='ContentWrite',
  full_name='tinyMQ.ContentWrite',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='tinyMQ.ContentWrite.id', index=0,
      number=1, type=7, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='topic', full_name='tinyMQ.ContentWrite.topic', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='body', full_name='tinyMQ.ContentWrite.body', index=2,
      number=3, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=116,
  serialized_end=171,
)


_POLL = _descriptor.Descriptor(
  name='Poll',
  full_name='tinyMQ.Poll',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='topic', full_name='tinyMQ.Poll.topic', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=173,
  serialized_end=194,
)


_ACK = _descriptor.Descriptor(
  name='Ack',
  full_name='tinyMQ.Ack',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='tinyMQ.Ack.id', index=0,
      number=1, type=7, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='flags', full_name='tinyMQ.Ack.flags', index=1,
      number=2, type=7, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=196,
  serialized_end=228,
)


_CONTENTREAD = _descriptor.Descriptor(
  name='ContentRead',
  full_name='tinyMQ.ContentRead',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='tinyMQ.ContentRead.id', index=0,
      number=1, type=7, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='status', full_name='tinyMQ.ContentRead.status', index=1,
      number=2, type=7, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='body', full_name='tinyMQ.ContentRead.body', index=2,
      number=3, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=230,
  serialized_end=285,
)

DESCRIPTOR.message_types_by_name['ConnInit'] = _CONNINIT
DESCRIPTOR.message_types_by_name['ConnStatus'] = _CONNSTATUS
DESCRIPTOR.message_types_by_name['ContentWrite'] = _CONTENTWRITE
DESCRIPTOR.message_types_by_name['Poll'] = _POLL
DESCRIPTOR.message_types_by_name['Ack'] = _ACK
DESCRIPTOR.message_types_by_name['ContentRead'] = _CONTENTREAD
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ConnInit = _reflection.GeneratedProtocolMessageType('ConnInit', (_message.Message,), {
  'DESCRIPTOR' : _CONNINIT,
  '__module__' : 'message_pb2'
  # @@protoc_insertion_point(class_scope:tinyMQ.ConnInit)
  })
_sym_db.RegisterMessage(ConnInit)

ConnStatus = _reflection.GeneratedProtocolMessageType('ConnStatus', (_message.Message,), {
  'DESCRIPTOR' : _CONNSTATUS,
  '__module__' : 'message_pb2'
  # @@protoc_insertion_point(class_scope:tinyMQ.ConnStatus)
  })
_sym_db.RegisterMessage(ConnStatus)

ContentWrite = _reflection.GeneratedProtocolMessageType('ContentWrite', (_message.Message,), {
  'DESCRIPTOR' : _CONTENTWRITE,
  '__module__' : 'message_pb2'
  # @@protoc_insertion_point(class_scope:tinyMQ.ContentWrite)
  })
_sym_db.RegisterMessage(ContentWrite)

Poll = _reflection.GeneratedProtocolMessageType('Poll', (_message.Message,), {
  'DESCRIPTOR' : _POLL,
  '__module__' : 'message_pb2'
  # @@protoc_insertion_point(class_scope:tinyMQ.Poll)
  })
_sym_db.RegisterMessage(Poll)

Ack = _reflection.GeneratedProtocolMessageType('Ack', (_message.Message,), {
  'DESCRIPTOR' : _ACK,
  '__module__' : 'message_pb2'
  # @@protoc_insertion_point(class_scope:tinyMQ.Ack)
  })
_sym_db.RegisterMessage(Ack)

ContentRead = _reflection.GeneratedProtocolMessageType('ContentRead', (_message.Message,), {
  'DESCRIPTOR' : _CONTENTREAD,
  '__module__' : 'message_pb2'
  # @@protoc_insertion_point(class_scope:tinyMQ.ContentRead)
  })
_sym_db.RegisterMessage(ContentRead)


# @@protoc_insertion_point(module_scope)
